language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_install:
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - npm install -g karma-cli
cache:
  directories:
    - "node_modules"
group: deprecated-2017Q4