language: node_js
node_js:
  - "8"
addons:
  chrome: beta
before_install:
  - npm install -g karma-cli
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"