language: node_js
node_js:
  - "6"
addons:
  firefox: "latest"
before_script:
  - npm install karma-cli -g
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  